In [46]:
import torch
import numpy as np

In [52]:
data = np.load('gameData.npz', allow_pickle=True)
X_train, Y_train, X_test, Y_test = data['array1'], data['array2'], data['array3'], data['array4']
    
model = torch.load("model")

for idx in np.random.randint(0, len(X_test), size=(3)):
    x = torch.tensor(X_test[idx])
    output = model(x.float()).unsqueeze(0)
    probVec = torch.nn.functional.softmax(output, dim=1).detach().numpy().squeeze()
    print(np.argmax(probVec))
    print(np.argmax(Y_test[idx]))
    print(probVec)
    print(Y_test[idx])
    print()

0
0
[1. 0. 0.]
[1. 0. 0.]

0
1
[1. 0. 0.]
[0. 1. 0.]

2
2
[0. 0. 1.]
[0. 0. 1.]



In [51]:
tallys = np.zeros((3, 3))
one = 0
for idx in range(len(X_test)):
    x = torch.tensor(X_test[idx])
    prediction = torch.argmax(model(x.float()))
    label = np.argmax(Y_test[idx])
    if prediction == label:
        tallys[prediction][0] += 1
    tallys[prediction][2] += 1
    tallys[label][1] += 1

for i in range(len(tallys)):
    print(f"Success Rate for {i}: {tallys[i][0] / tallys[i][1]}")
    print(f"{tallys[i][0]} / {tallys[i][1]}")
    print(f"'{i}' guessed {tallys[i][2]} times")
    print()

Success Rate for 0: 0.8435643564356435
852.0 / 1010.0
'0' guessed 1419.0 times

Success Rate for 1: 0.46421267893660534
454.0 / 978.0
'1' guessed 613.0 times

Success Rate for 2: 0.9555335968379447
967.0 / 1012.0
'2' guessed 968.0 times

